import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
      data-scroll-behavior="smooth"
    >
      <body className="">
        <Navbar />
        <div className="max-h-[90dvh] h-[90dvh] overflow-y-auto overflow-x-hidden custom-scrollbar">
          {children}
        </div>
      </body>
    </html>
  );
}
